Minor improvements.
vertyco/vrt-cogs pull request #34
Opened 2022-10-20 12:06 UTC by japandotorg

Even tho this PR was mainly made for hacktoberfest but since I use these cogs pretty frequently on my private bots, always wanted them add/remove commands to accept multiple inputs, hence this pull request.

2022-10-20 13:04 UTC, vertyco commented on nonuke/nonuke.py
> +            f"Successfully {'added' if add_or_remove.lower() == 'add' else 'removed'} {len([user for user in users])} users {'to' if add_or_remove.lower() == 'add' else 'from'} the whitelist."
Please make this handle plural and singular, for example if only adding 1 user it would not be `users`

2022-10-20 13:04 UTC, vertyco commented on support/commands.py
> +            f"Successfully {'added' if add_or_remove.lower() == 'add' else 'removed'} {len([role for role in roles])} roles {'to' if add_or_remove.lower() == 'add' else 'from'} support roles."
Handle plural and singular

2022-10-20 13:05 UTC, vertyco commented on support/commands.py
> +            f"Successfully {'added' if add_or_remove.lower() == 'add' else 'removed'} {len([user for user in users])} users {'to' if add_or_remove.lower() == 'add' else 'from'} the blacklist."
plural and singular `user`/`users` logic

2022-10-20 13:05 UTC, vertyco commented on tickets/commands.py
> -        To remove a role, simply run this command with it again to remove it
should be `to remove roles, `

2022-10-20 13:06 UTC, vertyco commented on tickets/commands.py
> +                f"Successfully {'added' if add_or_remove.lower() == 'add' else 'removed'} {len([user for user in users])} users {'to' if add_or_remove.lower() == 'add' else 'from'} the blacklist."
plural/singlular logic please

2022-10-20 16:26 UTC, japandotorg commented
> Overall I am okay with allowing users to add multiple roles or guild ids at a time, but there needs to be logic that handles the plural and singular of `user` or `users` in the response message

Alright I'll be adding them as soon as possible, if that's okay! Forgot to notice that beforehand.

2022-10-20 16:27 UTC, japandotorg commented
Also if you don't mind can this PR get the hacktoberfest label?

2022-10-20 19:29 UTC, japandotorg commented
I think that should be enough.

2022-10-20 20:08 UTC, vertyco requested changes
Could you also remove the unnecessary list comprehensions from the strings ie `len([guild for guild in guild_ids])`, if the length of something needs to be used it should be specified as a variable before hand instead of having it called every time.

For example it could jusf be `len(list(guild_ids))` if its a generator, and specify it as a variable before the ctx string as not not make things bloated

2022-10-21 18:43 UTC, japandotorg commented
Alright ig that should be it, lmk if there's anything else you'd like me to do :kappa:

2022-10-21 23:53 UTC, vertyco approved these changes

2022-10-21 23:53 UTC, merged

2022-10-23 06:21 UTC, vertyco commented
Having issues on dpy2

```py
Exception during loading of package
Traceback (most recent call last):
  File "/root/redenv/lib/python3.9/site-packages/redbot/core/core_commands.py", line 175, in _load
    await bot.load_extension(spec)
  File "/root/redenv/lib/python3.9/site-packages/redbot/core/bot.py", line 1597, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/.local/share/Red-DiscordBot/data/arkon/cogs/CogManager/cogs/nonuke/__init__.py", line 6, in <module>
    from .nonuke import NoNuke
  File "/root/.local/share/Red-DiscordBot/data/arkon/cogs/CogManager/cogs/nonuke/nonuke.py", line 8, in <module>
    class NoNuke(Listen, commands.Cog):
  File "/root/.local/share/Red-DiscordBot/data/arkon/cogs/CogManager/cogs/nonuke/nonuke.py", line 161, in NoNuke
    self, ctx: commands.Context, add_or_remove: commands.Literal["add", "remove"], users: commands.Greedy[discord.Member] = None
AttributeError: module 'redbot.core.commands' has no attribute 'Literal'

```